#!/bin/sh
. /etc/config/defines
usage="Usage: sys [-g|-s] [xml node] {value}"
case "$1" in
-g)
	echo [$0] get from script is deprecated !! > /dev/console
	;;
-s)
	case "$2" in
	configsave)
		rgcfg get -n $nvram -c /var/rgdb.xml.gz
		echo -ne "$image_sign\0" > /var/config.bin
		cat /var/rgdb.xml.gz >> /var/config.bin
		rm -f /var/rgdb.xml.gz
		;;
	restart)
		/etc/templates/wan.sh stop
		/etc/scripts/misc/nreboot.sh 3 &
		;;
	configrestore)
		;;
	factoryreset)
		/etc/templates/wan.sh stop
		/etc/scripts/misc/profile.sh reset
		/etc/scripts/misc/profile.sh put
		/etc/scripts/misc/nreboot.sh 3 &
		;;
	fwinfo)
		srv=`rgdb -g /sys/fwinfosrv`
		reqstr=`rgdb -g /sys/fwinfopath`
		reqstr="GET $reqstr HTTP/1.1
Accept: */*
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
Host: $srv
Connection: Close

"
		tcprequest "$reqstr" "$srv" 80 -f /var/run/fwinfo.html -t 5 -s
		parseinfo -f /var/run/fwinfo.html -t /var/run/fwinfo_t.html
		;;
	esac
	;;
*)
	echo $usage > /dev/console
	;;
esac
exit 0
