#!/bin/sh
usage="Usage: syslog [-g|-s] [xml node] {value}"
case "$1" in
-g)
	if [ "$2" = "entry#" ]; then
		pfile -c -f /var/log/messages
	else
		enty=`echo $2 | cut -d/ -f1`
		node=`echo $2 | cut -d/ -f2`
		en=`echo $enty | cut -d: -f1`
		id=`echo $enty | cut -d: -f2`
		if [ "$en" = "entry" ]; then
			case "$node" in
			datetime)
				pfile -f /var/log/messages -l$id | scut -f1 -n3
				;;
			message)
				pfile -f /var/log/messages -l$id | scut -p '|' -n1000
				;;
			esac
		fi
	fi
	;;
-s)
	log_path="/var/log/messages"
	tlog_path="/var/log/tlogsmsg"
	smtp_msg_path="/var/log/smtp_message.txt"
	case "$2" in
	tlogs)
		tlogs -l $log_path > $tlog_path
		;;
	clear)
		date_time=`date | scut -f2 -n3`
		echo "$date_time  |  SYS:038" > $log_path
		tlogs -l $log_path > $tlog_path
		;;
	sendmail)
		mail_server=`rgdb -g /sys/log/mailserver`
		email_addr=`rgdb -g /sys/log/email`
		mail_subject="Log Message."
		mail_port="25"
		src_host=`rgdb -g /sys/hostName`
		from=`rgdb -g /sys/log/email`
		reply=`rgdb -g /sys/log/email`

		tlogs -l $log_path > $tlog_path
		/usr/sbin/smtpclient -v -s "$mail_subject" -f "$from" -r "$reply" -H "$src_host" -S "$mail_server" -P "$mail_port" "$email_addr" < $tlog_path > $smtp_msg_path
		logger -p 192.1 "SYS:004[$email_addr]"
		;;
	*)
		echo $usage
		;;
	esac
	;;
*)
	echo $usage
	;;
esac
